name: wastefoodmanagement
description: A new Flutter project.
publish_to: 'none' # Remove this if you plan to publish

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4
  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.2.2
  location: ^8.0.0
  geolocator: ^14.0.0
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: 5.6.8
  
  # Make sure all other dependencies are included

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
