name: wastefoodmanagement
description: A new Flutter project.
publish_to: 'none' # Remove this if you plan to publish

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # ✅ Important fix here

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.4

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.1.0  # ✅ Added

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/  # ✅ Supports all images inside this folder
