// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7GniZlH86nQEFc9vzgeCILKgC1mUj2jM',
    appId: '1:502231044111:web:096d292e9bdbf15b2f537a',
    messagingSenderId: '502231044111',
    projectId: 'wastefoodmanagement-3be05',
    authDomain: 'wastefoodmanagement-3be05.firebaseapp.com',
    storageBucket: 'wastefoodmanagement-3be05.firebasestorage.app',
    measurementId: 'G-WT7BV8ZC9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFSppmDGAcH4ouej228VgF58tiaDNskwM',
    appId: '1:502231044111:android:f3abb49cb0ee453b2f537a',
    messagingSenderId: '502231044111',
    projectId: 'wastefoodmanagement-3be05',
    storageBucket: 'wastefoodmanagement-3be05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOHOPdJ8ut7qxkIPybr5mqC2nOOfH2sC4',
    appId: '1:502231044111:ios:2dc2640075f7fee82f537a',
    messagingSenderId: '502231044111',
    projectId: 'wastefoodmanagement-3be05',
    storageBucket: 'wastefoodmanagement-3be05.firebasestorage.app',
    iosBundleId: 'com.example.wastefoodmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOHOPdJ8ut7qxkIPybr5mqC2nOOfH2sC4',
    appId: '1:502231044111:ios:2dc2640075f7fee82f537a',
    messagingSenderId: '502231044111',
    projectId: 'wastefoodmanagement-3be05',
    storageBucket: 'wastefoodmanagement-3be05.firebasestorage.app',
    iosBundleId: 'com.example.wastefoodmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7GniZlH86nQEFc9vzgeCILKgC1mUj2jM',
    appId: '1:502231044111:web:2377c0b7d1590f6a2f537a',
    messagingSenderId: '502231044111',
    projectId: 'wastefoodmanagement-3be05',
    authDomain: 'wastefoodmanagement-3be05.firebaseapp.com',
    storageBucket: 'wastefoodmanagement-3be05.firebasestorage.app',
    measurementId: 'G-9DVW6B8ZE2',
  );
}
